import { exportUrl } from '../api.js'
import { ReleasePill, STATUS_LABELS } from '../components/badges.jsx'
import { Leaf } from '../components/Shell.jsx'
import { formatDateTime, shortId } from '../lib/format.js'

/**
 * Export (mockup #10). The evidence pack already exists on disk; this page
 * hands it over. PDF is not generated by the backend yet (EXECUTION_PLAN
 * S3.1), so that button says so instead of pretending.
 */

const FORMATS = [
  ['json', 'JSON — kết quả đầy đủ', 'result.json: mọi tuyên bố, bằng chứng, lập trường, rủi ro, pháp lý, cổng chất lượng.'],
  ['md', 'Markdown — gói bằng chứng', 'evidence_pack.md: bản đọc được, dùng để dán vào working paper.'],
  ['manifest', 'Manifest tái lập', 'manifest.json: config hash, hash đầu vào, kế hoạch chạy.'],
  ['audit', 'Nhật ký chạy (JSONL)', 'audit.jsonl: từng bước pipeline đã làm gì, theo thứ tự.'],
]

export default function ExportPage({ runId, runLabel, analysis, summary, reviewStates = {}, reviewDecisions = [] }) {
  const finalized = Object.values(reviewStates).filter((s) => s === 'FINALIZED').length
  const created = analysis?.manifest?.created_at

  const downloadReviews = () => {
    const blob = new Blob([JSON.stringify({ run_id: runId, states: reviewStates, decisions: reviewDecisions }, null, 2)], { type: 'application/json' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `greenscan-${runId}-reviews.json`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div className="grid gap-4 lg:grid-cols-[1fr_320px]">
      <div className="space-y-4">
        <section className="rounded-xl border border-slate-200 bg-white p-5">
          <h3 className="text-sm font-semibold text-slate-900">Định dạng</h3>
          <ul className="mt-3 space-y-2">
            {FORMATS.map(([f, label, hint]) => (
              <li key={f} className="flex items-start gap-3 rounded-lg border border-slate-200 p-3">
                <div className="flex-1">
                  <p className="text-sm font-medium text-slate-900">{label}</p>
                  <p className="text-xs text-slate-500">{hint}</p>
                </div>
                <a href={exportUrl(runId, f)} className="rounded-lg bg-[#0F3D2E] px-3 py-1.5 text-xs font-semibold text-white">Tải xuống</a>
              </li>
            ))}
            <li className="flex items-start gap-3 rounded-lg border border-slate-200 p-3">
              <div className="flex-1">
                <p className="text-sm font-medium text-slate-900">Quyết định người xem xét (JSON)</p>
                <p className="text-xs text-slate-500">{reviewDecisions.length} quyết định · {finalized} tuyên bố đã chốt — nhật ký append-only, nguồn của bộ gold.</p>
              </div>
              <button type="button" onClick={downloadReviews} className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700">Tải xuống</button>
            </li>
            <li className="flex items-start gap-3 rounded-lg border border-dashed border-slate-300 p-3 opacity-70">
              <div className="flex-1">
                <p className="text-sm font-medium text-slate-900">PDF — working paper</p>
                <p className="text-xs text-slate-500">Chưa có ở máy chủ (kế hoạch S3.1, tuần 28/09–04/10). Tạm thời dùng “In trang” trên màn tuyên bố hoặc Markdown ở trên.</p>
              </div>
              <span className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-400">Sắp có</span>
            </li>
          </ul>
        </section>

        <section className="rounded-xl border border-slate-200 bg-white p-5">
          <h3 className="text-sm font-semibold text-slate-900">Nội dung gói bằng chứng gồm</h3>
          <ul className="mt-2 grid gap-1 text-xs text-slate-700 sm:grid-cols-2">
            <li>✓ Thông tin phiên và manifest tái lập</li>
            <li>✓ Danh sách tuyên bố với 5 thuộc tính</li>
            <li>✓ Bằng chứng, trích dẫn trang, lập trường từng đoạn</li>
            <li>✓ Phép so sánh số liệu</li>
            <li>✓ Bối cảnh pháp lý theo ngày hiệu lực</li>
            <li>✓ Phân rã rủi ro theo rubric</li>
            <li>✓ 8 cổng chất lượng</li>
            <li>✓ Quyết định người xem xét (tệp riêng)</li>
          </ul>
        </section>
      </div>

      <aside className="rounded-xl border border-slate-200 bg-white p-5">
        <div className="rounded-lg border border-slate-200 bg-slate-50 p-4">
          <div className="flex items-center gap-1.5 text-[#0F3D2E]"><Leaf className="h-5 w-5" /><span className="text-sm font-bold">GreenScan</span></div>
          <p className="mt-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Hồ sơ kiểm chứng tuyên bố môi trường</p>
          <p className="mt-1 text-base font-semibold text-slate-900">{runLabel || 'Phiên chưa đặt tên'}</p>
          <p className="font-mono text-xs text-slate-500">run {shortId(runId, 16)}</p>
          <dl className="mt-3 space-y-1 text-xs">
            <div className="flex justify-between"><dt className="text-slate-500">Tạo lúc</dt><dd>{formatDateTime(created)}</dd></div>
            <div className="flex justify-between"><dt className="text-slate-500">Tài liệu</dt><dd className="font-mono">{analysis?.summary?.total_documents}</dd></div>
            <div className="flex justify-between"><dt className="text-slate-500">Tuyên bố</dt><dd className="font-mono">{analysis?.summary?.total_claims}</dd></div>
            <div className="flex justify-between"><dt className="text-slate-500">Đã chốt</dt><dd className="font-mono">{finalized}/{analysis?.summary?.total_claims}</dd></div>
            <div className="flex justify-between"><dt className="text-slate-500">Trạng thái</dt><dd><ReleasePill status={summary?.releaseStatus} /></dd></div>
          </dl>
          <ul className="mt-3 space-y-0.5 text-[11px] text-slate-600">
            {Object.entries(analysis?.summary?.status_counts || {}).map(([k, v]) => <li key={k} className="flex justify-between"><span>{STATUS_LABELS[k] || k}</span><span className="font-mono">{v}</span></li>)}
          </ul>
          <p className="mt-3 text-[10px] leading-relaxed text-slate-500">Kết quả ước lượng mức độ đầy đủ của bằng chứng, không phải kết luận pháp lý.</p>
        </div>
      </aside>
    </div>
  )
}
